apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-app
  replicas: 1
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-node
          image: gaijinwebdev/kub-first-app:2
